#!/bin/sh
# Startup script for protozoa
#
# chkconfig: 2345 96 04
# description: CCTV camera control translator and mixer
# pidfile: /var/run/protozoa.pid
#
# Source function library.
. /etc/rc.d/init.d/functions

[ -f /usr/local/bin/protozoa ] || exit 0

prog="protozoa"

start() {
    echo -n $"Starting $prog: " 
    daemon --user protozoa /usr/local/bin/protozoa
    RETVAL=$?
    if [ $RETVAL -ne 0 ]; then
	failure;
    fi;
    echo
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc protozoa
    RETVAL=$?
    if [ $RETVAL -ne 0 ]; then 
	failure;
    fi;
    echo
    return $RETVAL
}

case "$1" in
	start)
	    start
	    ;;
	
	stop)
	    stop
	    ;;
	
	status)
	    status protozoa
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart|status}"
	    exit 1

esac

exit $RETVAL
